name: example
description: Example app for Emirates ID Scanner package
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  eid_scanner:
    path: ../
  image_picker: ^1.0.4
  image_cropper: ^9.0.0

dev_dependencies:
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
