name: eid_scanner
description: A Flutter package to scan and parse Emirates ID cards.

version: 0.0.2
# publish_to: https://pub.dev

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_ml_kit: ^0.19.0
  intl: ^0.20.2
  camera: 0.10.4
  path_provider:
  image: ^3.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter
